version: "3"

services:

  pg:
    build:
      context: .
      dockerfile: dockerfiles/pg.Dockerfile
    restart: always
    env_file: botvars/$DOTENV_FILE

  pgmigrations:
    build:
      context: .
      dockerfile: dockerfiles/pgmigrations.Dockerfile
      args:
        - CMPDBOT_DIR
    restart: on-failure
    env_file: botvars/$DOTENV_FILE
    links:
      - pg:$POSTGRES_HOST

  s3:
    image: minio/minio
    restart: always
    environment:
      - MINIO_ACCESS_KEY
      - MINIO_SECRET_KEY
    command: server /data

#   adminsite:
#     build:
#       context: .
#       dockerfile: dockerfiles/adminsite.Dockerfile
#       args:
#         - CMPDBOT_DIR
#     restart: always
#     env_file: botvars/$DOTENV_FILE
#     links:
#       - pg:$POSTGRES_HOST
#       - pgmigrations:$PGMIGRATIONS_HOST
#     ports:
#       - $ADMINSITE_PORT:$ADMINSITE_PORT
