services:

  pg:
    build:
      context: .
      dockerfile: dockerfiles/pg.Dockerfile
    restart: always
    env_file: botvars/$DOTENV_FILE

  pgmigrations:
    build:
      context: .
      dockerfile: dockerfiles/pgmigrations.Dockerfile
    restart: on-failure
    env_file: botvars/$DOTENV_FILE
    links:
      - pg:$POSTGRES_HOST

  s3:
    image: minio/minio
    restart: always
    environment:
      - MINIO_ACCESS_KEY
      - MINIO_SECRET_KEY
    command: server /data

#   adminsite:
#     build:
#       context: .
#       dockerfile: dockerfiles/adminsite.Dockerfile
#     restart: always
#     env_file: $DOTENV_FILE
#     links:
#       - pg:$POSTGRES_HOST
#       # - s3:...
#     ports:
#       - $ADMINSITE_PORT:8000

  #bot

  #chooser

  #crons
