version: "3"

services:

  pg:
    build:
      context: .
      dockerfile: dockerfiles/pg.Dockerfile
    restart: always
    env_file: botvars/$DOTENV_FILE

  migrations:
    build:
      context: .
      dockerfile: dockerfiles/migrations.Dockerfile
      args:
        - CMPDBOT_DIR
    restart: on-failure
    env_file: botvars/$DOTENV_FILE
    links:
      - pg:$POSTGRES_HOST

  s3:
    image: minio/minio
    restart: always
    environment:
      MINIO_ACCESS_KEY: $S3_ACCESS_KEY
      MINIO_SECRET_KEY: $S3_SECRET_KEY
    command: server /data

  manage:
    build:
      context: .
      dockerfile: dockerfiles/manage.Dockerfile
      args:
        - CMPDBOT_DIR
    env_file: botvars/$DOTENV_FILE
    links:
      - pg:$POSTGRES_HOST
      - s3:$S3_HOST
    volumes:
      - $CMPDBOT_EXCHANGE_DIR_LOCAL:$CMPDBOT_EXCHANGE_DIR_CONTAINER

  bot:
    build:
      context: .
      dockerfile: dockerfiles/bot.Dockerfile
      args:
        - CMPDBOT_DIR
    restart: always
    env_file: botvars/$DOTENV_FILE
    links:
      - pg:$POSTGRES_HOST
      - s3:$S3_HOST
